default_postgresql_bin_path: /usr/lib/postgresql/{{ postgres_version }}/bin
default_postgresql_config_path: /etc/postgresql/{{ postgres_version }}/main
default_postgresql_data_dir: /var/lib/postgresql/{{ postgres_version }}/main
default_postgresql_daemon: postgresql@{{ postgres_version }}-main
default_postgresql_external_pid_file: /var/run/postgresql/{{ postgres_version }}-main.pid
